"""empty message

Revision ID: 0d877067a04c
Revises: fa3dc841a5ea
Create Date: 2022-01-13 14:00:55.049794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d877067a04c'
down_revision = 'fa3dc841a5ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('not_allocated', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'not_allocated')
    # ### end Alembic commands ###
