"""empty message

Revision ID: 2ae308f89fab
Revises: 
Create Date: 2022-01-13 11:30:24.686073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae308f89fab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('inventory', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inventory', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('warehouse', sa.Column('name', sa.String(length=200), nullable=True))
    op.add_column('warehouse', sa.Column('testing', sa.Integer(), nullable=False))
    op.alter_column('warehouse', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('warehouse', 'create_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse', sa.Column('create_time', sa.DATE(), autoincrement=False, nullable=True))
    op.alter_column('warehouse', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('warehouse', 'testing')
    op.drop_column('warehouse', 'name')
    op.alter_column('inventory', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
