"""empty message

Revision ID: c9c02fcb3267
Revises: 2ae308f89fab
Create Date: 2022-01-13 11:38:55.721488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c02fcb3267'
down_revision = '2ae308f89fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouse', 'testing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse', sa.Column('testing', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
