"""empty message

Revision ID: fa37ae227f6f
Revises: 0d877067a04c
Create Date: 2022-01-13 14:16:50.457015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa37ae227f6f'
down_revision = '0d877067a04c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('updated_time', sa.DateTime(), nullable=True))
    op.add_column('warehouse', sa.Column('updated_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouse', 'updated_time')
    op.drop_column('inventory', 'updated_time')
    # ### end Alembic commands ###
